export const COUNTRY_CODES: Record<string, string> = {
  'Mexico': 'MX', 'México': 'MX',
  'South Africa': 'ZA', 'África do Sul': 'ZA',
  'South Korea': 'KR', 'Coreia do Sul': 'KR',
  'Czech Republic': 'CZ', 'República Tcheca': 'CZ',
  'Canada': 'CA', 'Canadá': 'CA',
  'Bosnia & Herzegovina': 'BA', 'Bósnia e Herzegovina': 'BA', 'Bosnia e Herzegovina': 'BA',
  'Qatar': 'QA', 'Catar': 'QA',
  'Switzerland': 'CH', 'Suíça': 'CH',
  'Brazil': 'BR', 'Brasil': 'BR',
  'Morocco': 'MA', 'Marrocos': 'MA',
  'Haiti': 'HT',
  'Scotland': 'GB-SCT', 'Escócia': 'GB-SCT',
  'USA': 'US', 'Estados Unidos': 'US', 'EUA': 'US',
  'Paraguay': 'PY', 'Paraguai': 'PY',
  'Australia': 'AU', 'Austrália': 'AU',
  'Turkey': 'TR', 'Turquia': 'TR',
  'Germany': 'DE', 'Alemanha': 'DE',
  'Curaçao': 'CW',
  'Ivory Coast': 'CI', 'Costa do Marfim': 'CI',
  'Ecuador': 'EC', 'Equador': 'EC',
  'Netherlands': 'NL', 'Holanda': 'NL', 'Países Baixos': 'NL',
  'Japan': 'JP', 'Japão': 'JP',
  'Sweden': 'SE', 'Suécia': 'SE',
  'Tunisia': 'TN', 'Tunísia': 'TN',
  'Belgium': 'BE', 'Bélgica': 'BE',
  'Egypt': 'EG', 'Egito': 'EG',
  'Iran': 'IR', 'Irã': 'IR',
  'New Zealand': 'NZ', 'Nova Zelândia': 'NZ',
  'Spain': 'ES', 'Espanha': 'ES',
  'Cape Verde': 'CV', 'Cabo Verde': 'CV',
  'Saudi Arabia': 'SA', 'Arábia Saudita': 'SA',
  'Uruguay': 'UY', 'Uruguai': 'UY',
  'France': 'FR', 'França': 'FR',
  'Senegal': 'SN',
  'Iraq': 'IQ', 'Iraque': 'IQ',
  'Norway': 'NO', 'Noruega': 'NO',
  'Argentina': 'AR',
  'Algeria': 'DZ', 'Argélia': 'DZ',
  'Austria': 'AT', 'Áustria': 'AT',
  'Jordan': 'JO', 'Jordânia': 'JO',
  'Portugal': 'PT',
  'DR Congo': 'CD', 'RD Congo': 'CD',
  'Uzbekistan': 'UZ', 'Uzbequistão': 'UZ',
  'Colombia': 'CO', 'Colômbia': 'CO',
  'England': 'GB-ENG', 'Inglaterra': 'GB-ENG',
  'Croatia': 'HR', 'Croácia': 'HR',
  'Ghana': 'GH', 'Gana': 'GH',
  'Panama': 'PA', 'Panamá': 'PA'
};

export const getFlagCode = (team: string) => COUNTRY_CODES[team] || '';
